services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - INDEXER_NAME=${INDEXER_NAME}
      - RPC_ENDPOINT=${RPC_ENDPOINT}
      - START_BLOCK=${START_BLOCK}
      - FINALITY_CONFIRMATIONS=${FINALITY_CONFIRMATIONS}
      - CONTRACTS=${CONTRACTS}
      - ARCHIVE=${ARCHIVE}
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  indexer_network:
    driver: bridge
