services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - INDEXER_NAME=${INDEXER_NAME}
      - RPC_ENDPOINT=${RPC_ENDPOINT}
      - START_BLOCK=${START_BLOCK}
      - FINALITY_CONFIRMATIONS=${FINALITY_CONFIRMATIONS}
      - CONTRACTS=${CONTRACTS}
      - ARCHIVE=${ARCHIVE}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
      - MAX_BATCH_SIZE=${MAX_BATCH_SIZE}
      - RATE_LIMIT=${RATE_LIMIT}
      - RPC_CAPACITY=${RPC_CAPACITY}
      - CHRONOS_CONTRACT_ADDRESS=${CHRONOS_CONTRACT_ADDRESS}
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    restart: always
    networks:
      - indexer_network

networks:
  indexer_network:
    external: true