services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: postgres
    ports:
      - "23798:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  evm-indexer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  db_data:
