name: Indexer Deployment - Testnet
on:
  push:
    branches:
      - feature/deployment

jobs:

  deploy-indexers-mainnet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [neuroweb-testnet]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Inject environment variables
        run: |
          echo "DB_USER=${{ secrets[matrix.env | upper | replace('-', '_') + '_DB_USER'] }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets[matrix.env | upper | replace('-', '_') + '_DB_PASSWORD'] }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets[matrix.env | upper | replace('-', '_') + '_DB_NAME'] }}" >> $GITHUB_ENV
          echo "INDEXER_NAME=${{ matrix.env }}-indexer" >> $GITHUB_ENV
          echo "RPC_ENDPOINT=${{ secrets[matrix.env | upper | replace('-', '_') + '_RPC_ENDPOINT'] }}" >> $GITHUB_ENV
          echo "START_BLOCK=${{ secrets[matrix.env | upper | replace('-', '_') + '_RPC_ENDPOINT'] }}" >> $GITHUB_ENV
          echo "FINALITY_CONFIRMATIONS=${{ secrets[matrix.env | upper | replace('-', '_') + '_RPC_ENDPOINT'] }}" >> $GITHUB_ENV
          echo "CONTRACTS=${{ secrets[matrix.env | upper | replace('-', '_') + '_RPC_ENDPOINT'] }}" >> $GITHUB_ENV
          echo "ARCHIVE=${{ secrets[matrix.env | upper | replace('-', '_') + '_RPC_ENDPOINT'] }}" >> $GITHUB_ENV

      - name: Build and deploy
        run: |
          docker compose -f docker-compose.yml down ${{ matrix.env }}-indexer"
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml up -d ${{ matrix.env }}-indexer"
